### ISSUE TITLE
Only shows Disconnected on screen upon launch

### ISSUE THREAD

**Issue by dratereR** [lvnvceo/OllamaDroid#2]
Installed the APK and each time I open it, the screen shows Disconnected.

**Comment by EJolloX** [comment]
Hello, I downloaded and installed the release APK arm9, LegionY700, same problem. Disconneted and if I touch anything crashes. I tried to click the gear and same result.

**Comment by tristan-k** [comment]
+1

**Comment by Ac1drainn** [comment]
No longer maintained. Please find an alternative. If you do, please reply with a link here and I'll add it to the README.md
